# Generated by Django 4.1.2 on 2022-11-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_entregable_estudiante_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
